package diagnosis;

import drools.model.*;
import java.util.List;

rule "Find symptoms from diseases that match with patient symptoms"
    salience 30
    agenda-group "matching symptoms"
    lock-on-active true
    when
        $d: Disease(  disease != "first", disease != "second", disease != "third", $nonSpecificSymptoms: nonSpecificSymptoms)
        accumulate (
            $matchingSymptom: Symptom(this memberOf $nonSpecificSymptoms, text != "Oporavlja se od operacije"),
            $sum : count($matchingSymptom)
        )
    then
        System.out.println("Nasao" + $d.getDisease() + " - "+ $sum);
      //  modify($d) {setMatchingSymptoms($msNum)};
end